## Population
The entire group you want to study.

- Denoted by: **N** (size), **μ** (mean), **σ** (std dev)
- Example: All students in a country

## Sample
A subset selected from the population for analysis.

- Denoted by: **n** (size), **x̄** (mean), **s** (std dev)
- Example: 100 students from 5 universities

---

## Why Sampling?
- Cost-effective
- Time-saving
- Often it's impossible to observe the whole population

---

## Key Differences

| Feature            | Population                   | Sample                        |
|--------------------|------------------------------|-------------------------------|
| Size               | Usually large or infinite     | Small subset                  |
| Notation (mean)    | μ                            | x̄                            |
| Notation (std dev) | σ                            | s                             |
| Measurement        | Parameter                    | Statistic                     |
| Accuracy           | Exact (if measurable)         | Approximation                 |

---

In [4]:
import numpy as np
import pandas as pd

np.random.seed(42)
population = np.random.normal(loc=170, scale=10, size=10000)

# Sample of 100 people from the population
sample = np.random.choice(population, size=100, replace=False)

# Create a DataFrame
df = pd.DataFrame({
    'Population': population[:10],
    'Sample': np.append(sample[:10], [np.nan]*(10 - len(sample[:10])))
})

# Summary statistics
pop_mean = np.mean(population)
pop_std = np.std(population)
sample_mean = np.mean(sample)
sample_std = np.std(sample)

print(f"Population Mean (μ): {pop_mean:.2f}")
print(f"Population Std Dev (σ): {pop_std:.2f}")
print(f"Sample Mean (x̄): {sample_mean:.2f}")
print(f"Sample Std Dev (s): {sample_std:.2f}")

df

Population Mean (μ): 169.98
Population Std Dev (σ): 10.03
Sample Mean (x̄): 171.17
Sample Std Dev (s): 10.65

   Population      Sample
0  174.967142  176.904727
1  168.617357  186.259589
2  176.476885  166.066489
3  185.230299  168.036502
4  167.658466  157.064924
5  167.658630  175.510171
6  185.792128  160.066413
7  177.674347  171.642948
8  165.305256  160.448774
9  175.425600  138.295743