In [2]:
import pandas as pd

df = pd.read_csv("../../data/ucl202122/goals.csv")
df

,serial,player_name,club,position,goals,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,match_played
0,1,Benzema,Real Madrid,Forward,15,11,1,3,0,13,2,3,12
1,2,Lewandowski,Bayern,Forward,13,8,3,1,1,13,0,3,10
2,3,Haller,Ajax,Forward,11,3,4,3,1,11,0,1,8
3,4,Salah,Liverpool,Forward,8,0,8,0,0,7,1,1,13
4,5,Nkunku,Leipzig,Midfielder,7,3,1,3,0,7,0,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,73,Yansané,Sheriff,Forward,1,0,0,1,0,1,0,0,3
179,73,Yakhshiboev,Sheriff,Forward,1,0,0,1,0,1,0,0,3
180,73,Messias Junior,Milan,Forward,1,0,0,1,0,1,0,0,2
181,73,Morato,Benfica,Defender,1,0,0,1,0,1,0,0,2
182,73,Pedro Porro,Sporting CP,Defender,1,0,0,0,1,1,0,0,7

In [3]:
# Filter data
df = df[df["club"] == "Real Madrid"]
df

,serial,player_name,club,position,goals,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,match_played
0,1,Benzema,Real Madrid,Forward,15,11,1,3,0,13,2,3,12
13,12,Rodrygo,Real Madrid,Forward,5,2,2,1,0,5,0,0,10
18,16,Vinícius Júnior,Real Madrid,Forward,4,3,1,0,0,4,0,0,13
56,43,Kroos,Real Madrid,Midfielder,2,1,1,0,0,0,2,0,12
152,73,Alaba,Real Madrid,Defender,1,0,1,0,0,0,1,0,12
153,73,Asensio,Real Madrid,Forward,1,0,1,0,0,0,1,0,8

In [4]:

rows, column = df.shape

print("Number of rows: ", rows)
print("Number of columns: ", column)

# Shape mean dimensions of data frame

Number of rows:  6
Number of columns:  13